# -*- mode: makefile -*-
LATEX_ENGINE = <%= latex_engine %>
LATEX_FLAGS  =

exam.pdf: exam.tex
	$(LATEX_ENGINE) $(LATEX_FLAGS) exam.tex

.PHONY: clean
clean:
	rm -f *.{log,aux,out,dvi,ps,toc,amc,pag}
